import fs from 'fs';
import path from 'path';

import _ from 'lodash';

const template = component => `<h1 class="unmodified-component">${component.name}</h1>\n`;
const style = component => `${component.name} { }\n`;
const directive = component => `module.exports = () => ({
  restrict: 'E',
  template: require('./template.html'),
  controller: ['$scope', $scope => {

  }]
});`;

const moduleIndex = (function(module) {
  const moduleName = module.name;

  const onNewLineIfExists = value => value ? `\n${value}` : '';
  const printComponents = (indent, components) =>

`${(components || [])
      .map(
        ({name, path, components}) =>
            `${indent}.directive('${name}',${Array(Math.max(1, 33 - name.length - indent.length)).join(' ')}require('${path}'))${onNewLineIfExists(printComponents(indent + '  ', components))}`
      ).join('\n')
}`;

  const printFactories = (indent, factories) =>

`${(factories || [])
      .map(
        ({name, path, factories}) =>
            `${indent}.factory('${name}',${Array(Math.max(1, 33 - name.length - indent.length)).join(' ')}require('${path}'))${onNewLineIfExists(printFactories(indent + '  ', factories))}`
      ).join('\n')
}`;

  const printConfigs = (indent, configs) =>
`${
  (configs || []).map(config => `${indent}.config(require('./${config}'))`)
}`;

  return ({name, requirements, components, factories, routes, configs}) =>

`/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */
require('angular');

${(requirements || []).map(({jsPackageName, moduleName}) => jsPackageName ? `require('${jsPackageName}');`
                                                                          : `import ${moduleName} from '../${moduleName}';`).join('\n')}

export default {
  '${name}': angular.module('${name}', [${(requirements || []).map(({moduleName}) => `'${moduleName}'`).join(', ')}])
${printComponents('    ', components)}
${printFactories('    ', factories)}
${printConfigs('    ', configs)}
};
/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */
`;

})(module);

const createConfig = config =>
`export default [() => {

}];`;


export function toAngularProject(project) {
  const projectRoot = `${project.name}`,
        modulesRoot = path.join(projectRoot, 'modules');

  createDirectory(projectRoot);
  createDirectory(modulesRoot);

  project.modules.forEach(processModule);

  function processModule(module) {
    const moduleRoot = path.join(modulesRoot, module.name),
          directivesRoot = path.join(moduleRoot, 'directives'),
          factoriesRoot = path.join(moduleRoot, 'factories');

    createDirectory(moduleRoot);

    if (module.components) processComponents(module.components);
    if (module.factories) processFactories(module.factories);
    if (module.configs) processConfigs(module.configs);

    createModuleIndex(module);

    function processComponents(components) {
      createDirectory(directivesRoot);

      components.forEach(componentProcessor(directivesRoot));

      function componentProcessor(root, parent = {path: `./directives`}) {
        return component => {
          component.path = `${parent.path}/${component.name}`; // mutation
          component.components.forEach(componentProcessor(prepareDirectory(component), component));
        };

        function prepareDirectory(component) {
          const componentRoot = path.join(root, component.name);

          createDirectory(componentRoot);
          createFiles(componentRoot, component);

          return componentRoot;
        }

        function createFiles(directory, component) {
          const root = path.join(directory, component.name);

          createFileIfNotExists(path.join(directory, 'template.html'), template(component));
          createFileIfNotExists(path.join(directory, 'style.less'), style(component));
          createFileIfNotExists(path.join(directory, 'index.js'), directive(component));
        }
      }
    }

    function processFactories(factories) {
      createDirectory(factoriesRoot);

      factories.forEach(factoryProcessor(factoriesRoot));

      function factoryProcessor(root, parent = {path: `./factories`}) {
        return factory => {
          factory.path = `${parent.path}/${factory.name}`; // mutation
          factory.factories.forEach(factoryProcessor(prepareDirectory(factory), factory));
        };

        function prepareDirectory(factory) {
          const factoryRoot = path.join(root, factory.name);

          createDirectory(factoryRoot);
          createFiles(factoryRoot, factory);

          return factoryRoot;
        }

        function createFiles(directory, factory) {
          const root = path.join(directory, factory.name);

          createFileIfNotExists(path.join(directory, 'index.js'), directive(factory));
        }
      }
    }

    function processConfigs(configs) {
      configs.forEach(config => createFileIfNotExists(path.join(moduleRoot, `${config}.js`), createConfig(config)));
    }

    function createModuleIndex(module) {
      createFile(path.join(moduleRoot, 'index.js'), moduleIndex(module));
    }
  }
}

function createDirectory(directory) {
  if (!fs.existsSync(directory)) {
    console.log(`Creating D '${directory}'`);
    fs.mkdirSync(directory);
  }
}

function createFileIfNotExists(path, content) {
  if (!fs.existsSync(path)) createFile(path, content);
}

function createFile(path, content) {
  console.log(`Creating F '${path}'`);
  fs.writeFileSync(path, content);
}